update

diff --git a/.github/workflows/feature.yml b/.github/workflows/feature.yml
--- a/.github/workflows/feature.yml
+++ b/.github/workflows/feature.yml
@@ -37,11 +37,19 @@ on:
 jobs:
   # job-name
   checks:
+    runs-on: ubuntu-latest 
     # gate keeper conditions
-    if: ${{ startsWith(github.ref, 'refs/heads/feature') }}
     steps:
-      - name: Check branch
-        run: echo valid branch
+      - name: Checkout Repository
+        uses: actions/checkout@v4 #https://github.com/actions/checkout
+      - name: Check Branch Name
+        run: |
+          if [[ "${GITHUB_REF}" =~ ^refs/heads/feature/[^/]+$ ]]; then
+            echo "Branch name matches the pattern 'feature/' without additional subdirectories."
+          else
+            echo "Branch name does not match the pattern 'feature/' or has additional subdirectories."
+            exit 1  # Optionally, exit with a non-zero status to fail the workflow
+          fi
   run:
     # depends on other job(s)
     needs: checks
@@ -53,7 +61,7 @@ jobs:
         working-directory: ./test-app
     steps:
       # packages and dependencies (fill accordingly to your needs)
-      - name: Checkout
+      - name: Checkout Repository
         uses: actions/checkout@v4 #https://github.com/actions/checkout
       - name: Setup Node  
         uses: actions/setup-node@v4 #https://github.com/actions/setup-node
